### PR TITLE
#15 - Migrated pom.xml to com.jcabi parent

### PR DESCRIPTION
**Pull request by olegmoz**

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 I can review this one, please assign me

**Comment by 0crat** [comment]
This pull request [#17](https://github.com/artipie/nuget-adapter/issues/17) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/946a5968-bf91-4ba7-8907-01d3b2b0f682); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by yegor256** [comment]
@olegmoz why not our `ppom` parent? It's even better than jcabi.

**Comment by olegmoz** [comment]
@yegor256 okey, will try it. Thought it is not ready yet

**Comment by olegmoz** [comment]
@yegor256 used ppom, please review

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda) didn't make CR comments

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
