### PR TITLE
#43 - Using InMemoryStorage in tests instead of FileStorage in tests

### PR DESCRIPTION
**Pull request by olegmoz**
Closes issue #43 
Replaced FileStorage with InMemoryStorage in tests

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 I'm available, please assign me

**Comment by g4s8** [comment]
@0crat elect

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/artipie/nuget-adapter/issues/44#issuecomment-594370001))

@g4s8 The job [#44](https://github.com/artipie/nuget-adapter/issues/44) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/05204086-bd97-4c1b-bf01-68ac7795562d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by paulodamaso** [comment]
@g4s8 please merge

**Comment by 0crat** [comment]
Job was finished in 6 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
