### PR TITLE
#78 - Organized HTTP service production and tests classes by service

### LINKED ISSUE #78: Poor structure of `com.artipie.nuget.http`
HTTP related production & test classes in `com.artipie.nuget.http` are poorly structured, some are arranged by service and some are not.

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #78

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#79](https://github.com/artipie/nuget-adapter/issues/79) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9bcef0cc-572a-4978-8ccf-10bf4cce6175); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by olegmoz** [comment]
@Vatavuk fixed all the comments, please review

**Comment by olegmoz** [comment]
@g4s8 recent changes to actions you've made in master are breaking the build, please fix

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Vatavuk** [comment]
@g4s8 ping

**Comment by 0crat** [comment]
Code review was too long (8 days), architects (@g4s8) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@Vatavuk please make sure your CR comments would be mostly about design problems, but NOT rather cosmetic issues

**Comment by Vatavuk** [comment]
@sereshqua ok

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
