### PR TITLE
#76 - Fixed package name com.artpie.nuget -> com.artipie.nuget

### LINKED ISSUE #76: `com.artpie.nuget` package name contains typo
All code in project is in package `com.artpie.nuget`. it should be renamed to ``com.artipie.nuget``

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #76

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#77](https://github.com/artipie/nuget-adapter/issues/77) is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7d870d74-6904-4237-bdb1-866a84b67a9f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by HDouss** [comment]
@g4s8 Good to merge.

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dc9a75c2-99a9-40a1-bc27-ddaf8f08c10c, thread: pool-916-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.12](https://github.com/zerocracy/farm): Issue: artipie/nuget-adapter#77, Comment: 619909156

**Comment by HDouss** [comment]
> @0crat quality bad

Do you really think any comment could be made in this PR?

**Comment by sereshqua** [comment]
@HDouss I do, because I am the policy keeper 💯 . 

PR with NO issues found by code reviewer = bad quality :)

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/artipie/nuget-adapter/issues/77#issuecomment-619912274); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by HDouss** [comment]
> @HDouss I do, because I am the policy keeper 💯 .
> 
> PR with NO issues found by code reviewer = bad quality :)

@sereshqua Some PR like this one could not have issues. It would be insane to make a comment on a PR like this one, where what is asked is renaming a package.

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
