### PR TITLE
#1 - Added pom.xml, .gitattributes & some additions to .gitignore

### PR DESCRIPTION
**Pull request by olegmoz**

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#2](https://github.com/artipie/nuget-adapter/issues/2) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8345c05a-41d4-42fa-a6d6-6fe649d3d3a7); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/artipie/nuget-adapter/issues/2#issuecomment-579667518))

@g4s8 The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#2](https://github.com/artipie/nuget-adapter/issues/2), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/nuget-adapter#2` is not assigned, can't get start time

**Comment by 0crat** [comment]
This pull request [#2](https://github.com/artipie/nuget-adapter/issues/2) is assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3c20749a-b528-4173-93ad-0fb4d27eda42); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by iakunin** [comment]
@g4s8 seems that 0crat got out of control =)

**Comment by g4s8** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/artipie/nuget-adapter/issues/2#issuecomment-579723460))

@g4s8 The user @iakunin[/z](https://www.0crat.com/u/iakunin) resigned from [#2](https://github.com/artipie/nuget-adapter/issues/2), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#2](https://github.com/artipie/nuget-adapter/issues/2) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/98621ab8-cfde-4fc2-94f2-2bef880ab71f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat resign

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/nuget-adapter/issues/2#issuecomment-579732272))

@g4s8 Job `gh:artipie/nuget-adapter#2` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/artipie/nuget-adapter/issues/2#issuecomment-579732254))

@g4s8 The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#2](https://github.com/artipie/nuget-adapter/issues/2), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/nuget-adapter/issues/2#issuecomment-579732272))

@g4s8 Pull request [#2](https://github.com/artipie/nuget-adapter/issues/2) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
