### PR TITLE
feat: added functionality to delete package from index

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #221 
Added functionality to delete package from index and test.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@dgarus please, review

**Review by dgarus — CHANGES_REQUESTED** [review]
@olenagerasimova thanks!
Minor comments.

**Comment by olenagerasimova** [comment]
@dgarus thanks, corrected. I've introduced the method in `Update` class as it's just some sort of helper and it is not meant to be public (on interface level).

**Review by dgarus — APPROVED** [review]
@olenagerasimova thanks!
LGTM

**Pull request merged**
