### PR TITLE
#21 - Moving new package when it is added to repository

### PR DESCRIPTION
**Pull request by olegmoz**
Closes issue #21 
When package is added it is moved to proper location instead of copying.

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 I'm available, please assign me

**Comment by 0crat** [comment]
This pull request [#56](https://github.com/artipie/nuget-adapter/issues/56) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/55fe554f-446f-4a09-b173-9a5910feb219); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 19 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @vatavuk[/z](https://www.0crat.com/u/vatavuk)[/z](https://www.0crat.com/u/vatavuk) didn't make CR comments

**Pull request merged**
