### PR TITLE
#22 - Extracted PackageId class

### PR DESCRIPTION
**Pull request by olegmoz**
Issue #22 
Extracted PackageId class to encapsulate package versions enumeration storage key generation.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#27](https://github.com/artipie/nuget-adapter/issues/27) is assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/761fdd04-5983-42f6-9494-26f153c9ac91); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by olegmoz** [comment]
@olenagerasimova thank you for your input! Made changes by your comments, please review

**Comment by olegmoz** [comment]
@olenagerasimova please re-review the changes, as the approve became stale after merging in master branch

**Comment by olegmoz** [comment]
@g4s8 please review

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)[/z](https://www.0crat.com/u/olenagerasimova) didn't make CR comments

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
