### PR TITLE
#45 - Migrated to HTTP 0.5

### PR DESCRIPTION
**Pull request by olegmoz**
Closes issue #45 
Migration to HTTP 0.5

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#46](https://github.com/artipie/nuget-adapter/issues/46) is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f76483f7-4bfc-4f72-8cfa-617baf916227); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by olegmoz** [comment]
@HDouss good idea! Changed java version to 1.8, please review

**Comment by HDouss** [comment]
@g4s8 Good for me. Please merge.

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @hdouss[/z](https://www.0crat.com/u/hdouss)[/z](https://www.0crat.com/u/hdouss) didn't make CR comments

**Comment by 0crat** [comment]
Job was finished in 18 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
