### PR TITLE
#84 - Added headers to Reosurce.get method

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #84 
Added headers parameter, as they will be required for request authentication.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#86](https://github.com/artipie/nuget-adapter/issues/86) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0bd57655-f7e0-4b15-8aa4-f49accfff054); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 I'm not sure this is clear to me if it's needed or not as it does not solve the issue itself nor introduce todos to continue the work, but from a REV point of view, this looks good to me.

**Comment by victornoel** [comment]
@g4s8 ping

**Comment by 0crat** [comment]
Job `gh:artipie/nuget-adapter#86` is not assigned, can't get performer

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/nuget-adapter/issues/86#issuecomment-633595132))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#86](https://github.com/artipie/nuget-adapter/issues/86) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fnuget-adapter%2386%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@g4s8 I think 0crat missed this one too

**Comment by g4s8** [comment]
@0crat pay 15min @victornoel

**Comment by victornoel** [comment]
@g4s8 I got paid but I don't know why the job is still in my agenda...

**Pull request merged**
